### ISSUE TITLE
How does one format stdin?

### ISSUE THREAD

**Issue by augustebaum** [omnilib/ufmt#122]
`ufmt` is awesome, thanks a bunch! I already use the `pre-commit` hook, but I'd like to auto-format as well. 
With my editor (helix) I need to write the auto-format command with this kind of syntax:
```toml
formatter = { command = "black", args = ["-", "-q"] }
```
but I can't seem to do it with `ufmt`.

In fact, when I try with
```toml
formatter = { command = "ufmt", args = ["-q", "format"] }
```
it actually deletes the whole contents of the file instead of formatting.

Am I just misunderstanding something or is there no way to format text from stdin?

**Comment by amyreese** [comment]
`ufmt format -` will format stdin, though I would recommend passing the file path as well, so that appropriate configuration and first-party module detection can work correctly:

```
ufmt format - <path/to/file>
```

**Comment by augustebaum** [comment]
Thanks, this seems to work!
