### ISSUE TITLE
Importing version from __version__.py makes building conda-forge packages awkward

### ISSUE THREAD

**Issue by dstoeckel** [omnilib/ufmt#123]
First of all *thank you* for µfmt, it is a really useful addition to my CI pipelines. So useful, that I am in the process of packaging it for conda-forge.

While creating the package I, however, ran into an issue that makes the build process less optimal than it could be. As µfmt is using flit_core as metadata backend, the pip build process will run flit_core during build time. As a step of this, flit is trying to determine the package version from `__init__.py`. It does so using two passes:

1. An AST-based pass that tries to find an assignment of the form `__version__ = "x.y.z"`
2. An import based pass that loads the package and then inspects the `__version__` variable.

For µfmt, pass 1) fails as the __version__ variable is defined in `__version__.py`. This leads to pass 2) being run, which succeeds. However in the conda-forge build environment, runtime dependencies are not installed by default, leading to a build failure. Thus, as a workaround, we need to add the relevant runtime dependencies to the build step, which is non-ideal but works.

Please consider defining `__version__` directly in `__init__.py` to allow making the conda-forge package more straightforward.

Link to the conda-forge pull request for reference: https://github.com/conda-forge/staged-recipes/pull/20527

P.S.: the same behavior can be observed for trailrunner and stdlibs. For the latter no failure happens as there are no additional dependencies though. Please let me know in case you consider a change and I can open separate issues.

**Comment by amyreese** [comment]
The version is in a separate file so that it can be easily generated/written by the "attribution" tool that also manages the changelog and git tags. There might be alternatives to make this work in flit-core, and I'll look into that and let you know.

**Comment by amyreese** [comment]
This should be resolved when building with the latest version of flit-core.
